version: '3'

services:
  account-service:
    build:
      context: ./account-service
    ports:
      - "8081:8080"
    depends_on:
      - mysql-account

  customer-service:
    build:
      context: ./customer-service
    ports:
      - "8082:8080"
    depends_on:
      - mysql-customer

  transaction-service:
    build:
      context: ./transaction-service
    ports:
      - "8083:8080"
    depends_on:
      - mysql-transaction

  api-gateway:
    build:
      context: ./api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - account-service
      - customer-service
      - transaction-service

  mysql-account:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: account_db
    ports:
      - "3306:3306"

  mysql-customer:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: customer_db
    ports:
      - "3307:3306"

  mysql-transaction:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: transaction_db
    ports:
      - "3308:3306"
